-- ============================================================
-- Event-Driven POC Schema
-- ============================================================
-- Purpose:
--   Model the event-driven version of the same architecture:
--     raw data table
--       -> trigger creates event queue row
--       -> trigger sends pg_notify()
--       -> Python worker LISTENs for notification
--       -> worker claims event
--       -> worker processes associated raw rows
--       -> worker marks event processed
-- ============================================================


-- ============================================================
-- Cleanup
-- ============================================================

DROP TRIGGER IF EXISTS notify_poc_raw_data_after_insert_event_queue
ON public.notify_poc_raw_data;

DROP FUNCTION IF EXISTS public.notify_poc_raw_data_insert_event_queue();

DROP TABLE IF EXISTS public.notify_poc_event_queue;
DROP TABLE IF EXISTS public.notify_poc_raw_data;


-- ============================================================
-- Raw data table
-- ============================================================

CREATE TABLE public.notify_poc_raw_data (
    notify_poc_raw_data_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name varchar(256) NOT NULL,
    processing_timestamp timestamptz(6) NOT NULL,
    value double precision NULL,

    created_time_stamp timestamptz(6) DEFAULT current_timestamp NULL,
    origin_time_stamp timestamptz(6) NULL,

    data_source_id int NOT NULL DEFAULT 0
);


-- ============================================================
-- Event queue table
-- ============================================================
-- Same role as polling_poc_event_queue.
-- Difference is that inserts into raw data also send pg_notify().
-- ============================================================

CREATE TABLE public.notify_poc_event_queue (
    notify_poc_event_queue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    min_raw_data_id bigint NOT NULL,
    max_raw_data_id bigint NOT NULL,
    row_count int NOT NULL,

    status varchar(32) NOT NULL DEFAULT 'unprocessed',

    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    started_at timestamptz(6) NULL,
    processed_at timestamptz(6) NULL,

    worker_id text NULL,
    error_message text NULL,

    CONSTRAINT notify_poc_event_queue_status_check
    CHECK (status IN ('unprocessed', 'processing', 'processed', 'failed')),

    CONSTRAINT notify_poc_event_queue_raw_id_check
    CHECK (min_raw_data_id <= max_raw_data_id),

    CONSTRAINT notify_poc_event_queue_row_count_check
    CHECK (row_count > 0)
);


-- ============================================================
-- Indexes
-- ============================================================

-- Supports fetching raw rows for an event.
CREATE INDEX notify_poc_raw_data_id_idx
ON public.notify_poc_raw_data (notify_poc_raw_data_id);

-- Supports time-based inspection/debugging.
CREATE INDEX notify_poc_raw_data_created_time_stamp_idx
ON public.notify_poc_raw_data (created_time_stamp DESC);

-- Supports worker lookup for unprocessed events.
CREATE INDEX notify_poc_event_queue_unprocessed_idx
ON public.notify_poc_event_queue (created_at, notify_poc_event_queue_id)
WHERE status = 'unprocessed';

-- Supports inspecting processing latency/results.
CREATE INDEX notify_poc_event_queue_status_created_idx
ON public.notify_poc_event_queue (status, created_at);


-- ============================================================
-- Trigger function
-- ============================================================
-- Creates one event queue row for each INSERT statement and sends
-- a notification to wake the event-driven Python worker.
--
-- Important:
--   The event queue table is still the durable source of work.
--   pg_notify() is only a wake-up signal.
-- ============================================================

CREATE OR REPLACE FUNCTION public.notify_poc_raw_data_insert_event_queue()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_event_id bigint;
    inserted_row_count int;
BEGIN
    INSERT INTO public.notify_poc_event_queue (
        min_raw_data_id,
        max_raw_data_id,
        row_count
    )
    SELECT
        min(notify_poc_raw_data_id),
        max(notify_poc_raw_data_id),
        count(*)
    FROM new_data
    RETURNING
        notify_poc_event_queue_id,
        row_count
    INTO
        inserted_event_id,
        inserted_row_count;

    PERFORM pg_notify(
        'notify_poc_event_queue_inserted',
        json_build_object(
            'event_id', inserted_event_id,
            'row_count', inserted_row_count
        )::text
    );

    RETURN NULL;
END;
$$;


-- ============================================================
-- Trigger
-- ============================================================

CREATE TRIGGER notify_poc_raw_data_after_insert_event_queue
AFTER INSERT ON public.notify_poc_raw_data
REFERENCING NEW TABLE AS new_data
FOR EACH STATEMENT
EXECUTE FUNCTION public.notify_poc_raw_data_insert_event_queue();


-- ============================================================
-- Grants
-- ============================================================

GRANT ALL PRIVILEGES ON TABLE public.notify_poc_raw_data
TO "fsd_staging_fm-readwrite";

GRANT ALL PRIVILEGES ON TABLE public.notify_poc_event_queue
TO "fsd_staging_fm-readwrite";

GRANT ALL PRIVILEGES ON FUNCTION public.notify_poc_raw_data_insert_event_queue()
TO "fsd_staging_fm-readwrite";

GRANT USAGE, SELECT, UPDATE
ON SEQUENCE public.notify_poc_raw_data_notify_poc_raw_data_id_seq
TO "fsd_staging_fm-readwrite";

GRANT USAGE, SELECT, UPDATE
ON SEQUENCE public.notify_poc_event_queue_notify_poc_event_queue_id_seq
TO "fsd_staging_fm-readwrite";


-- ============================================================
-- Optional: fully remove POC objects
-- ============================================================

/*
DROP TRIGGER IF EXISTS notify_poc_raw_data_after_insert_event_queue
ON public.notify_poc_raw_data;

DROP FUNCTION IF EXISTS public.notify_poc_raw_data_insert_event_queue();

DROP TABLE IF EXISTS public.notify_poc_event_queue;
DROP TABLE IF EXISTS public.notify_poc_raw_data;
*/