-- ============================================================
-- Polling POC Schema
-- ============================================================
-- Purpose:
--   Model the current architecture:
--     raw data table
--       -> trigger creates event queue row
--       -> polling worker polls event queue
--       -> worker claims event
--       -> worker processes associated raw rows
--       -> worker marks event processed
-- ============================================================


-- ============================================================
-- Cleanup
-- ============================================================

DROP TRIGGER IF EXISTS polling_poc_raw_data_after_insert_event_queue
ON public.polling_poc_raw_data;

DROP FUNCTION IF EXISTS public.polling_poc_raw_data_insert_event_queue();

DROP TABLE IF EXISTS public.polling_poc_event_queue;
DROP TABLE IF EXISTS public.polling_poc_raw_data;


-- ============================================================
-- Raw data table
-- ============================================================

CREATE TABLE public.polling_poc_raw_data (
    polling_poc_raw_data_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name varchar(256) NOT NULL,
    processing_timestamp timestamptz(6) NOT NULL,
    value double precision NULL,

    created_time_stamp timestamptz(6) DEFAULT current_timestamp NULL,
    origin_time_stamp timestamptz(6) NULL,

    data_source_id int NOT NULL DEFAULT 0
);


-- ============================================================
-- Event queue table
-- ============================================================
-- One event queue row represents one INSERT statement into
-- polling_poc_raw_data.
--
-- min_raw_data_id / max_raw_data_id allow the worker to fetch the
-- raw rows associated with this event.
-- ============================================================

CREATE TABLE public.polling_poc_event_queue (
    polling_poc_event_queue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    min_raw_data_id bigint NOT NULL,
    max_raw_data_id bigint NOT NULL,
    row_count int NOT NULL,

    status varchar(32) NOT NULL DEFAULT 'unprocessed',

    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    started_at timestamptz(6) NULL,
    processed_at timestamptz(6) NULL,

    worker_id text NULL,
    error_message text NULL,

    CONSTRAINT polling_poc_event_queue_status_check
    CHECK (status IN ('unprocessed', 'processing', 'processed', 'failed')),

    CONSTRAINT polling_poc_event_queue_raw_id_check
    CHECK (min_raw_data_id <= max_raw_data_id),

    CONSTRAINT polling_poc_event_queue_row_count_check
    CHECK (row_count > 0)
);


-- ============================================================
-- Indexes
-- ============================================================

-- Supports fetching raw rows for an event.
CREATE INDEX polling_poc_raw_data_id_idx
ON public.polling_poc_raw_data (polling_poc_raw_data_id);

-- Supports time-based inspection/debugging.
CREATE INDEX polling_poc_raw_data_created_time_stamp_idx
ON public.polling_poc_raw_data (created_time_stamp DESC);

-- Supports polling worker lookup for unprocessed events.
CREATE INDEX polling_poc_event_queue_unprocessed_idx
ON public.polling_poc_event_queue (created_at, polling_poc_event_queue_id)
WHERE status = 'unprocessed';

-- Supports inspecting processing latency/results.
CREATE INDEX polling_poc_event_queue_status_created_idx
ON public.polling_poc_event_queue (status, created_at);


-- ============================================================
-- Trigger function
-- ============================================================
-- This creates one event queue row for each INSERT statement.
--
-- Example:
--   INSERT INTO polling_poc_raw_data (...)
--   SELECT ...
--   FROM generate_series(1, 100);
--
-- Result:
--   100 raw rows
--   1 event queue row
-- ============================================================

CREATE OR REPLACE FUNCTION public.polling_poc_raw_data_insert_event_queue()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.polling_poc_event_queue (
        min_raw_data_id,
        max_raw_data_id,
        row_count
    )
    SELECT
        min(polling_poc_raw_data_id),
        max(polling_poc_raw_data_id),
        count(*)
    FROM new_data;

    RETURN NULL;
END;
$$;


-- ============================================================
-- Trigger
-- ============================================================

CREATE TRIGGER polling_poc_raw_data_after_insert_event_queue
AFTER INSERT ON public.polling_poc_raw_data
REFERENCING NEW TABLE AS new_data
FOR EACH STATEMENT
EXECUTE FUNCTION public.polling_poc_raw_data_insert_event_queue();


-- ============================================================
-- Grants
-- ============================================================

GRANT ALL PRIVILEGES ON TABLE public.polling_poc_raw_data
TO "fsd_staging_fm-readwrite";

GRANT ALL PRIVILEGES ON TABLE public.polling_poc_event_queue
TO "fsd_staging_fm-readwrite";

GRANT ALL PRIVILEGES ON FUNCTION public.polling_poc_raw_data_insert_event_queue()
TO "fsd_staging_fm-readwrite";

GRANT USAGE, SELECT, UPDATE
ON SEQUENCE public.polling_poc_raw_data_polling_poc_raw_data_id_seq
TO "fsd_staging_fm-readwrite";

GRANT USAGE, SELECT, UPDATE
ON SEQUENCE public.polling_poc_event_queue_polling_poc_event_queue_id_seq
TO "fsd_staging_fm-readwrite";


-- ============================================================
-- Optional: fully remove POC objects
-- ============================================================

/*
DROP TRIGGER IF EXISTS polling_poc_raw_data_after_insert_event_queue
ON public.polling_poc_raw_data;

DROP FUNCTION IF EXISTS public.polling_poc_raw_data_insert_event_queue();

DROP TABLE IF EXISTS public.polling_poc_event_queue;
DROP TABLE IF EXISTS public.polling_poc_raw_data;
*/